CUDA_VISIBLE_DEVICES=2 \
python train.py \
        -task global \
        -model bert \
        -train queries=/data2/jindawei/data/msmarco-doctrain-queries.tsv,docs=/data2/jindawei/data/msmarco-docs-firstP_title.tsv,qrels=/data2/jindawei/data/msmarco/rerank_doc/msmarco-doctrain-qrels.tsv,trec=/data2/jindawei/data/bids_marco-doc_ance-firstp-10_global.tsv \
        -max_input 40000000 \
        -save ./checkpoints/gltr_global_n10_w1 \
        -dev /data2/jindawei/data/dev_valid_1200_subset_from-splitidx-0.top100_n10_with1.jsonl \
        -qrels /data2/jindawei/data/msmarco-docdev-qrels.tsv \
        -vocab bert-base-uncased \
        -pretrain bert-base-uncased \
        -res ./results/gltr_global_n10_w1.trec \
        -metric mrr_cut_100 \
        -max_query_len 64 \
        -max_doc_len 445 \
        -epoch 1 \
        -optimizer adamw \
        -batch_size 10 \
        -lr 2e-5 \
        -gradient_accumulation_steps 4 \
        -n_warmup_steps 2000 \
        -logging_step 10 \
        -eval_every 10